name: flutter_google_map
description: "Flutter demo of Google Maps with place search and driving directions."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  location: 7.0.1
  google_place: ^0.4.7
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
